# Project information
site_name: MuData
site_url: https://your-site.com
site_author: MuData Team
site_description: Data management and analytics platform

# Copyright
copyright: Copyright &copy; 2025 MuData

# Favicon
extra:
  favicon: img/cow.svg

# Configuration
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: indigo
      accent: blue
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: indigo
      accent: blue
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.action.edit
  
  # Custom templates
  custom_dir: docs/overrides
  icon:
    logo: material/book-open-variant
  font:
    text: Roboto
    code: Roboto Mono

# Extensions
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - toc:
      permalink: true

# Plugins
plugins:
  - search

# Navigation
docs_dir: docs
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - Guide:
    - Writing: guide/writing.md
    - Styling: guide/styling.md
  - Reference:
    - Commands: reference/commands.md
    - Settings: reference/settings.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-username
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/your-username
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/your-username

# Build options
use_directory_urls: true
strict: true

# Custom CSS and Icons
extra_css:
  - https://cdn.jsdelivr.net/npm/@mdi/font@7.2.96/css/materialdesignicons.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css
  - styles/extra.css

# Enable Material Icons
extra_javascript:
  - https://cdn.jsdelivr.net/npm/@mdi/font@7.2.96/scripts/materialdesign-icons.min.js

